apiVersion: apimanagement.gloo.solo.io/v2
kind: ApiDoc
metadata:
  name: adservice
  namespace: online-boutique
spec:
  graphql:
    schemaDefinition: |-
      type Ad { redirectUrl: String text: String }

      type AdList { ads: [Ad] }

      type Query {
        GetAds(context_keys: [String]): AdList
      }
---
apiVersion: apimanagement.gloo.solo.io/v2
kind: ApiDoc
metadata:
  name: products
  namespace: online-boutique
spec:
  graphql:
    schemaDefinition: |-
      type Price { currency_code: String units: String nanos: Int }

      type Product { 
        id: String
        name: String
        description: String
        picture: String
        categories: [String]
        price_usd: Price
      }

      type ProductList { products: [Product] }

      type Query {
        ListProducts: ProductList
        GetProduct(id: String): Product
      }
---
apiVersion: apimanagement.gloo.solo.io/v2
kind: ApiDoc
metadata:
  name: currencies
  namespace: online-boutique
spec:
  graphql:
    schemaDefinition: |-
      type CurrencyCodes { currency_codes: [String] }

      type Currency {
        currency_code: String
        nanos: Int
        units: Int
      }

      type CurrencyConversion {
        from: Currency
        to_code: String
      }

      type Query {
        GetCurrencies: [CurrencyCodes]
        ConvertCurrency(request CurrencyConversion): Currency
      }
