apiVersion: security.policy.gloo.solo.io/v2
kind: CORSPolicy
metadata:
  name: cors-policy
  namespace: online-boutique
spec:
  applyToRoutes:
  - route:
      labels:
        ingress: all
  config:
    allowCredentials: true
    allowHeaders:
    - content-type
    allowMethods:
    - POST
    allowOrigins:
    - regex: '.*'