apiVersion: apimanagement.gloo.solo.io/v2
kind: GraphQLResolverMap
metadata:
  name: adservice
  namespace: online-boutique
spec:
  types:
    Query:
      fields:
        GetAds:
          variables:
            context_keys:
              graphqlArg: context_keys
            resolverResultVar:
              resolverResult: {}
          resolvers:
          - restResolver:
              destinations:
              - port:
                  number: 9560
                ref:
                  cluster: cluster-1
                  name: adservice
                  namespace: online-boutique
              request:
                headers:
                  :method:
                    json: POST
                  :path:
                    json: /ads
                body:
                  jq: '{ context_keys: .context_keys }'
            resolverResultTransform:
              jq: '{ads: .resolverResultVar.ads}'
---
apiVersion: apimanagement.gloo.solo.io/v2
kind: GraphQLResolverMap
metadata:
  name: products
  namespace: online-boutique
spec:
  types:
    Query:
      fields:
        ListProducts:
          variables:
            productVar:
              graphqlArg: context_keys
            resolverResultVar:
              resolverResult: {}
          resolvers:
          - restResolver:
              destinations:
              - port:
                  number: 3555
                ref:
                  cluster: cluster-1
                  name: productcatalogservice
                  namespace: online-boutique
              request:
                headers:
                  :method:
                    json: GET
                  :path:
                    json: /products
            resolverResultTransform:
              jq: '{}'
        GetProduct:
          variables:
            productVar:
              graphqlArg: id
            resolverResultVar:
              resolverResult: {}
          resolvers:
          - restResolver:
              destinations:
              - port:
                  number: 3555
                ref:
                  cluster: cluster-1
                  name: productcatalogservice
                  namespace: online-boutique
              request:
                headers:
                  :method:
                    json: GET
                  :path:
                    jq: '"/products/id/" + (.productVar | tostring)'
            resolverResultTransform:
              jq: '{products: .resolverResultVar.products}'