apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: podinfo-frontend
  namespace: podinfo-frontend
spec:
  options:
    eastWestGateways:
    - selector:
        labels:
          istio: eastwestgateway
    federation:
      enabled: false
    serviceIsolation:
      enabled: true
      trimProxyConfig: true