{{- if $.Values.istioInstallations.enabled }}
{{- range $index, $gateway := $.Values.istioInstallations.northSouthGateways }}
{{- if $gateway.enabled }}
{{- if ne $index 0 }}
---
{{- end }} 
apiVersion: admin.gloo.solo.io/v2
kind: GatewayLifecycleManager
metadata:
  name: {{ $gateway.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  installations:
    # ns gateway installation
{{- range $install := $gateway.installations }}
    - gatewayRevision: {{ $install.gatewayRevision }}
    {{- if $install.clusters }}
    {{- range $cluster := $install.clusters }}
      clusters: 
        - name: {{ $cluster.name }}
          activeGateway: {{ $cluster.activeGateway }}
    {{- end }}
    {{- else }}
      clusters: 
        - name: {{ $.Values.common.cluster }}
          activeGateway: true
    {{- end }}
      istioOperatorSpec:
{{ mergeOverwrite (include "northSouthGateways.iopSpec" (dict "Values" $.Values  "Release" $.Release "gateway" $gateway) | fromYaml) $install.istioOperatorSpec | toYaml | indent 8 }}
{{- end }}
{{- end }}  {{/* if Values.northSouthGateways.enabled */}}
{{- end }}  {{/* range */}}
{{- end }}
