apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gloo-cluster2
  region: us-east-2
  version: "1.21"

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 2
    privateNetworking: true
