apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: bookinfo-routetable
  namespace: bookinfo-frontends
spec:
  hosts:
  - '*'
  http:
  - forwardTo:
      destinations:
      - port:
          number: 9080
        ref:
          name: productpage
          namespace: bookinfo-frontends
    matchers:
    - uri:
        exact: /productpage
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    name: productpage
  virtualGateways:
  - name: north-south-gw
    namespace: istio-gateways