apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak-setup
  namespace: keycloak
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloak-setup-admin
  namespace: gloo-mesh
subjects:
- kind: ServiceAccount
  name: keycloak-setup
  namespace: keycloak
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
# bitnami/kubectl:latest
apiVersion: v1
kind: Pod
metadata:
  name:  keycloak-setup
  namespace: keycloak
  labels:
    app: keycloak-setup
spec:
  serviceAccountName: keycloak-setup
  containers:
    - command:
        - sleep
        - "20h"
      image: bitnami/kubectl:1.22.11-debian-11-r4
      name: keycloak-setup
  