{{- $rateLimiter := $.Values.rateLimiter }}
{{- if $rateLimiter.enabled }}
{{- $rateLimiterImage := $rateLimiter.rateLimiter.image }}

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rate-limiter
  {{- include "rate-limiter.extraLabels" . | nindent 4 }}
  name: rate-limiter
  namespace: {{ $.Values.common.addonNamespace | default $.Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: rate-limiter
      rate-limiter: rate-limiter
  template:
    metadata:
      labels:
        app: rate-limiter
        rate-limiter: rate-limiter
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9091"
        prometheus.io/scrape: "true"
        {{- include "rate-limiter.extraTemplateAnnotations" . | nindent 8 }}
    spec:
      serviceAccountName: rate-limiter
      containers:
      - image: {{ printf "%v/%v:%v" $rateLimiterImage.registry $rateLimiterImage.repository $rateLimiterImage.tag | quote }}
        imagePullPolicy: {{ $rateLimiterImage.pullPolicy }}
        name: rate-limiter
        env:
        - name: LOG_LEVEL
          value: {{ $rateLimiter.rateLimiter.logLevel }}
        - name: START_STATS_SERVER
          value: "true"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- if $rateLimiter.rateLimiter.watchNamespace }}
        - name: WATCH_NAMESPACE
          value: "{{ $rateLimiter.rateLimiter.watchNamespace }}"
        {{- end }}
        - name: RL_PORT_GRPC
          value: "{{ $rateLimiter.rateLimiter.ports.grpc }}"
        - name: READY_PORT_HTTP
          value: "{{ $rateLimiter.rateLimiter.ports.ready }}"
        - name: DEBUG_PORT
          value: "{{ $rateLimiter.rateLimiter.ports.debug }}"
        - name: REDIS_URL
          value: {{ $rateLimiter.redis.hostname }}:{{ $rateLimiter.redis.service.port }}
        {{- if $rateLimiter.redis.clustered  }}
        - name: REDIS_CLUSTERED_MODE
          value: {{ $rateLimiter.redis.clustered }}
        {{- end}}
        - name: REDIS_SOCKET_TYPE
          value: {{ $rateLimiter.redis.service.socket }}
        {{- if $rateLimiter.redis.certs.enabled }}
        - name: REDIS_CA_CERT
          value: {{ $rateLimiter.redis.certs.mountPoint }}/{{ $rateLimiter.redis.certs.caCert }}
        {{- end }}
        {{- if $rateLimiter.redis.auth.enabled }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ $rateLimiter.redis.auth.secretName }}
              key:  {{ $rateLimiter.redis.auth.passwordKey }}
        - name: REDIS_USER
          valueFrom:
            secretKeyRef:
              name: {{ $rateLimiter.redis.auth.secretName }}
              key:  {{ $rateLimiter.redis.auth.usernameKey }}
        {{- end}}
        - name: READY_PATH_HTTP
          value: "{{ $rateLimiter.rateLimiter.readyPath }}"
        - name: ALIVE_PATH_HTTP
          value: "{{ $rateLimiter.rateLimiter.alivePath }}"
        readinessProbe:
          httpGet:
            port: {{ $rateLimiter.rateLimiter.ports.ready }}
            path: {{ $rateLimiter.rateLimiter.readyPath }}
          initialDelaySeconds: 1
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
{{- if $rateLimiter.rateLimiter.alivePath }}
        livenessProbe:
          httpGet:
            port: {{ $rateLimiter.rateLimiter.ports.ready }}
            path: {{ $rateLimiter.rateLimiter.alivePath }}
          initialDelaySeconds: 3
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
{{- end}}
        {{- if $rateLimiter.redis.certs.enabled }}
        volumeMounts:
          - mountPath: {{ $rateLimiter.redis.certs.mountPoint }}
            name: tls-volume
        {{- end }}          
{{- if $rateLimiter.rateLimiter.resources }}
        resources:
{{ toYaml $rateLimiter.rateLimiter.resources | indent 10}}
{{- else}}
        resources:
          requests:
            cpu: 500m
            memory: 256Mi
{{- end}}
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      {{- if $rateLimiter.redis.certs.enabled }}
      volumes:
      - name: tls-volume
        secret:
          secretName: {{ $rateLimiter.redis.certs.secretName }}
      {{- end }}
---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: rate-limiter
  {{- include "rate-limiter.extraLabels" . | nindent 4 }}
  name: rate-limiter
  namespace: {{ $.Values.common.addonNamespace | default $.Release.Namespace }}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: rate-limiter
  {{- include "rate-limiter.extraLabels" . | nindent 4 }}
  name: rate-limiter
  namespace: {{ $.Values.common.addonNamespace | default $.Release.Namespace }}
spec:
  selector:
    app: rate-limiter
    rate-limiter: rate-limiter
  type: ClusterIP
  ports:
  - name: grpc
    port: {{ $rateLimiter.rateLimiter.ports.grpc }}
  - name: ready
    port: {{ $rateLimiter.rateLimiter.ports.ready }}
  - name: debug
    port: {{ $rateLimiter.rateLimiter.ports.debug }}
{{- end }}