{{- $rateLimiter := $.Values.rateLimiter }}
{{- if $rateLimiter.enabled }}
{{- if and $rateLimiter.rateLimiter.installClusterRoles }}
kind: ClusterRole
{{- else}}
kind: Role
{{- end}}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rate-limiter
  namespace: {{ $.Values.common.addonNamespace | default $.Release.Namespace }}
  labels:
    app: rate-limiter
  {{- include "rate-limiter.extraLabels" . | nindent 4 }}
rules:
- apiGroups:
  - ratelimit.solo.io
  resources:
  - ratelimitconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ratelimit.solo.io
  resources:
  - ratelimitconfigs/status
  verbs:
  - get
  - update

---
{{- if $rateLimiter.rateLimiter.installClusterRoles }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end}}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rate-limiter
  namespace: {{ $.Values.common.addonNamespace | default $.Release.Namespace }}
  labels:
    app: rate-limiter
  {{- include "rate-limiter.extraLabels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: rate-limiter
  namespace: {{ $.Values.common.addonNamespace | default $.Release.Namespace }}
roleRef:
  {{- if $rateLimiter.rateLimiter.installClusterRoles }}
  kind: ClusterRole
  {{- else}}
  kind: Role
  {{- end}}
  name: rate-limiter
  apiGroup: rbac.authorization.k8s.io
{{- end}}
