# WorkspaceSettings enable application owners to configure and overwrite what their workspaces are importing, 
# what their workspaces are exporting to, along with configuration options such as service isolation or federation. 
# WorkspaceSettings for ops-team:
apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: ops-team
  namespace: ops-team
spec:
  importFrom:
  - workspaces:
    - name: dev-team # Need to pick up the RouteTables from dev-team
  exportTo:
  - workspaces:
    - name: "*"
    resources:
    - kind: SERVICE # Workloads need to talk to ext-auth and rate-limit pods
      namespace: gloo-gateway-addons
---
# WorkspaceSettings for dev-team:
apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: dev-team
  namespace: dev-team
spec:
  importFrom:
  - workspaces:
    - name: ops-team # Workloads need to talk to ext-auth and rate-limit pods
  exportTo:
  - workspaces:
    - name: ops-team # Export our frontend RouteTables
