# Configuration for the Gloo agent.
glooAgent:
  enabled: true
  relay:
    clientTlsSecret:
      name: gloo-agent-tls-cert
    # With this override, we don't have to create a mock relay-identity-token-secret
    tokenSecret:
      key: null
      name: null
      namespace: null
