common:
  # Name of the cluster. Be sure to modify this value to match your cluster's name.
  cluster: "mgmt-cluster"

# Configuration for the Gloo management server.
glooMgmtServer:
  enabled: true
  relay:
    disableTokenGeneration: true
    disableCa: true
    disableCaCertGeneration: true
    tlsSecret:
      name: gloo-server-tls-cert

# Configuration for the Gloo UI.
glooUi:
  enabled: true

# Gloo Platform Redis configuration options.
redis:
  deployment:
    enabled: true

# Helm values for configuring Prometheus. See the [Prometheus Helm chart](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml) for the complete set of values.
prometheus:
  enabled: false

# OTLP collector for workload cluster collectors
telemetryGateway:
  enabled: false