# Cluster name
common:
  cluster: mgmt-cluster.spoc.nicklab.com

# OTLP collector for workload cluster collectors
telemetryGateway:
  enabled: true
  ports:
    otlp:
      containerPort: 55690
      enabled: true
      protocol: TCP
      servicePort: 55690
  image:
    tag: 2.3.3
# dont try and generate the token
glooMgmtServer:
  enabled: false
  relay:
    disableTokenGeneration: true

# Optional customization for the Gloo Platform Telemetry Collector.
telemetryGatewayCustomization:
  disableDefaultPipeline: true
  # Disable cert generation for the Gloo Platform Telemetry Gateway.
  disableCertGeneration: true
  extraReceivers:
    otlp/mtls:
      protocols:
        grpc:
          endpoint: 0.0.0.0:55690
          tls:
            client_ca_file: /etc/otel-certs/ca.crt
            cert_file: /etc/otel-certs/tls.crt
            key_file: /etc/otel-certs/tls.key
  extraExporters:
    otlp/tracing:
      endpoint: jaeger-collector.monitoring.svc.cluster.local:4317
      tls:
        insecure: true
  extraPipelines:
    metrics/same:
      receivers:
      - otlp/mtls
      processors:
      - memory_limiter
      - batch
      exporters:
      - prometheus
    traces/gloo-mesh:
      receivers:
      - otlp/mtls
      processors: 
      - batch
      exporters: 
      - otlp/tracing