apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gloo-cluster1
  region: us-west-2
  version: "1.25"


nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 2
    privateNetworking: true