apiVersion: trafficcontrol.policy.gloo.solo.io/v2
kind: HeaderManipulationPolicy
metadata:
  name: cluster2
  namespace: backend-apis-team
spec:
  applyToRoutes:
  - withDestinations:
      selector:
        cluster: cluster2
  config:
    appendResponseHeaders:
      x-cluster-name: "cluster2"
      x-cluster-locality: "us-west-2a"