apiVersion: v1
kind: Namespace
metadata:
  name: web-ui
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: view-nodes
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-nodes
subjects:
- kind: ServiceAccount
  name: frontend
  namespace: web-ui
roleRef:
  kind: ClusterRole
  name: view-nodes
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: frontend
      containers:
        - name: server
          image: gcr.io/solo-test-236622/frontend:solo-build
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
              httpHeaders:
                - name: "Cookie"
                  value: "shop_session-id=x-readiness-probe"
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
              httpHeaders:
                - name: "Cookie"
                  value: "shop_session-id=x-liveness-probe"
          env:
            - name: PORT
              value: "8080"
            - name: AD_SERVICE_ADDR
              value: "ads.backend-apis-team.solo-io.mesh:80"
            - name: CART_SERVICE_ADDR
              value: "cart.backend-apis-team.solo-io.mesh:80"
            - name: RECOMMENDATION_SERVICE_ADDR
              value: "recommendations.backend-apis-team.solo-io.mesh:80"
            - name: SHIPPING_SERVICE_ADDR
              value: "shipping.backend-apis-team.solo-io.mesh:80"
            - name: CHECKOUT_SERVICE_ADDR
              value: "checkout.backend-apis-team.solo-io.mesh:80"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "product-catalog.backend-apis-team.solo-io.mesh:80"
            - name: CURRENCY_SERVICE_ADDR
              value: "currency.backend-apis-team.solo-io.mesh:80"
            # # ENV_PLATFORM: One of: local, gcp, aws, azure, onprem
            # # When not set, defaults to "local" unless running in GKE, otherwies auto-sets to gcp 
            - name: ENV_PLATFORM 
              value: "onprem"
            - name: DISABLE_TRACING
              value: "1"
            - name: DISABLE_PROFILER
              value: "1"
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KUBERNETES_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_CLUSTER_NAME
              value: cluster2
          # - name: JAEGER_SERVICE_ADDR
          #   value: "jaeger-collector:14268"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
