{{ $sidecarAccel := $.Values.sidecarAccel }}
{{- if $sidecarAccel.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $sidecarAccel.fullname }}
  namespace: {{ $.Values.common.addonNamespace | default $.Release.Namespace }}
  labels:
    {{- include "sidecar-accel.labels" . | nindent 4 }}
{{- end }}
