apiVersion: admin.gloo.solo.io/v2
kind: GatewayLifecycleManager
metadata:
  name: istio-ingressgateway
  namespace: gloo-mesh
spec:
  installations:
      # The revision for this installation, such as 1-14
    - gatewayRevision: 1-13
      # List all workload clusters to install Istio into
      clusters:
      - name: cluster1
        # If set to true, the spec for this revision is applied in the cluster
        activeGateway: true
      - name: cluster2
        activeGateway: true
      istioOperatorSpec:
        # No control plane components are installed
        profile: empty
        # Solo.io Istio distribution repository; required for Gloo Istio.
        # You get the repo key from your Solo Account Representative.
        hub: us-docker.pkg.dev/gloo-mesh/istio-workshops
        # The Solo.io Gloo Istio tag
        tag: 1.13.8-solo
        components:
          ingressGateways:
          # Enable the default ingress gateway
            - name: istio-ingressgateway
              # Deployed to gloo-mesh-gateways by default
              namespace: istio-gateways
              enabled: true
              #label:
                # Set a unique label for the gateway. This is required to
                # ensure Gateways can select this workload
                #  istio: ingressgateway
                #  app: istio-ingressgateway
              k8s:
                service:
                  type: LoadBalancer
                  selector:
                    istio: ingressgateway
                  # Default ports
                  ports:
                    # Port for health checks on path /healthz/ready.
                    # For AWS ELBs, this port must be listed first.
                    - name: status-port
                      port: 15021
                      targetPort: 15021
                    # Main HTTP ingress port
                    - port: 80
                      targetPort: 8080
                      name: http2
                    # Main HTTPS ingress port
                    - port: 443
                      targetPort: 8443
                      name: https
