apiVersion: v1
kind: Namespace
metadata:
  name: http-client
  namespace: http-client
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: http-client
  namespace: http-client
---
apiVersion: v1
kind: Service
metadata:
  name: http-client
  namespace: http-client
  labels:
    app: http-client
    service: http-client
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: http-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-client
  namespace: http-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-client
  template:
    metadata:
      labels:
        app: http-client
    spec:
      serviceAccountName: http-client
      containers:
      - image: curlimages/curl:7.81.0
        imagePullPolicy: IfNotPresent
        name: http-client
        ports:
        - containerPort: 80
        command:
        - sleep
        - 20h