apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-cert
  namespace: istio-gateways
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
spec:
  secretName: tls-secret
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  subject:
    organizations:
    - solo.io
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
  - '*'
  issuerRef:
    name: gateway-ca
    kind: ClusterIssuer
    group: cert-manager.io