# apiVersion: apimanagement.gloo.solo.io/v2
# kind: ApiDoc
# metadata:
#   name: gql
#   namespace: online-boutique
# spec:
#   graphql:
#     schemaDefinition: |-
#       type Price { currency_code: String units: String nanos: Int }

#       type Product { 
#         id: String
#         name: String
#         description: String
#         picture: String
#         categories: [String]
#         price_usd: Price
#       }

#       type ProductList { products: [Product] }

#       type Ad { redirect_url: String text: String }

#       type CartItem {
#          product_id: String
#          quantity: Int
#       }

#       type AdList { ads: [Ad] }

#       type UserCart { items: [CartItem] user_id: String! }

#       type Query {
#         ListProducts: ProductList
#         GetAds: AdList
#         GetCart(user_id: String): UserCart
#       }
# ---
# apiVersion: apimanagement.gloo.solo.io/v2
# kind: ApiDoc
# metadata:
#   name: hipster-schema
#   namespace: online-boutique
# spec:
#   grpc:
#     descriptors:
#       Cu0hCg1wYi9kZW1vLnByb3RvEgtoaXBzdGVyc2hvcCJFCghDYXJ0SXRlbRIdCgpwcm9kdWN0X2lkGAEgASgJUglwcm9kdWN0SWQSGgoIcXVhbnRpdHkYAiABKAVSCHF1YW50aXR5IlQKDkFkZEl0ZW1SZXF1ZXN0EhcKB3VzZXJfaWQYASABKAlSBnVzZXJJZBIpCgRpdGVtGAIgASgLMhUuaGlwc3RlcnNob3AuQ2FydEl0ZW1SBGl0ZW0iKwoQRW1wdHlDYXJ0UmVxdWVzdBIXCgd1c2VyX2lkGAEgASgJUgZ1c2VySWQiKQoOR2V0Q2FydFJlcXVlc3QSFwoHdXNlcl9pZBgBIAEoCVIGdXNlcklkIkwKBENhcnQSFwoHdXNlcl9pZBgBIAEoCVIGdXNlcklkEisKBWl0ZW1zGAIgAygLMhUuaGlwc3RlcnNob3AuQ2FydEl0ZW1SBWl0ZW1zIgcKBUVtcHR5IlYKGkxpc3RSZWNvbW1lbmRhdGlvbnNSZXF1ZXN0EhcKB3VzZXJfaWQYASABKAlSBnVzZXJJZBIfCgtwcm9kdWN0X2lkcxgCIAMoCVIKcHJvZHVjdElkcyI+ChtMaXN0UmVjb21tZW5kYXRpb25zUmVzcG9uc2USHwoLcHJvZHVjdF9pZHMYASADKAlSCnByb2R1Y3RJZHMiugEKB1Byb2R1Y3QSDgoCaWQYASABKAlSAmlkEhIKBG5hbWUYAiABKAlSBG5hbWUSIAoLZGVzY3JpcHRpb24YAyABKAlSC2Rlc2NyaXB0aW9uEhgKB3BpY3R1cmUYBCABKAlSB3BpY3R1cmUSLwoJcHJpY2VfdXNkGAUgASgLMhIuaGlwc3RlcnNob3AuTW9uZXlSCHByaWNlVXNkEh4KCmNhdGVnb3JpZXMYBiADKAlSCmNhdGVnb3JpZXMiSAoUTGlzdFByb2R1Y3RzUmVzcG9uc2USMAoIcHJvZHVjdHMYASADKAsyFC5oaXBzdGVyc2hvcC5Qcm9kdWN0Ughwcm9kdWN0cyIjChFHZXRQcm9kdWN0UmVxdWVzdBIOCgJpZBgBIAEoCVICaWQiLQoVU2VhcmNoUHJvZHVjdHNSZXF1ZXN0EhQKBXF1ZXJ5GAEgASgJUgVxdWVyeSJIChZTZWFyY2hQcm9kdWN0c1Jlc3BvbnNlEi4KB3Jlc3VsdHMYASADKAsyFC5oaXBzdGVyc2hvcC5Qcm9kdWN0UgdyZXN1bHRzIm4KD0dldFF1b3RlUmVxdWVzdBIuCgdhZGRyZXNzGAEgASgLMhQuaGlwc3RlcnNob3AuQWRkcmVzc1IHYWRkcmVzcxIrCgVpdGVtcxgCIAMoCzIVLmhpcHN0ZXJzaG9wLkNhcnRJdGVtUgVpdGVtcyJBChBHZXRRdW90ZVJlc3BvbnNlEi0KCGNvc3RfdXNkGAEgASgLMhIuaGlwc3RlcnNob3AuTW9uZXlSB2Nvc3RVc2QibwoQU2hpcE9yZGVyUmVxdWVzdBIuCgdhZGRyZXNzGAEgASgLMhQuaGlwc3RlcnNob3AuQWRkcmVzc1IHYWRkcmVzcxIrCgVpdGVtcxgCIAMoCzIVLmhpcHN0ZXJzaG9wLkNhcnRJdGVtUgVpdGVtcyI0ChFTaGlwT3JkZXJSZXNwb25zZRIfCgt0cmFja2luZ19pZBgBIAEoCVIKdHJhY2tpbmdJZCKPAQoHQWRkcmVzcxIlCg5zdHJlZXRfYWRkcmVzcxgBIAEoCVINc3RyZWV0QWRkcmVzcxISCgRjaXR5GAIgASgJUgRjaXR5EhQKBXN0YXRlGAMgASgJUgVzdGF0ZRIYCgdjb3VudHJ5GAQgASgJUgdjb3VudHJ5EhkKCHppcF9jb2RlGAUgASgFUgd6aXBDb2RlIlgKBU1vbmV5EiMKDWN1cnJlbmN5X2NvZGUYASABKAlSDGN1cnJlbmN5Q29kZRIUCgV1bml0cxgCIAEoA1IFdW5pdHMSFAoFbmFub3MYAyABKAVSBW5hbm9zIkcKHkdldFN1cHBvcnRlZEN1cnJlbmNpZXNSZXNwb25zZRIlCg5jdXJyZW5jeV9jb2RlcxgBIAMoCVINY3VycmVuY3lDb2RlcyJcChlDdXJyZW5jeUNvbnZlcnNpb25SZXF1ZXN0EiYKBGZyb20YASABKAsyEi5oaXBzdGVyc2hvcC5Nb25leVIEZnJvbRIXCgd0b19jb2RlGAIgASgJUgZ0b0NvZGUi5gEKDkNyZWRpdENhcmRJbmZvEiwKEmNyZWRpdF9jYXJkX251bWJlchgBIAEoCVIQY3JlZGl0Q2FyZE51bWJlchImCg9jcmVkaXRfY2FyZF9jdnYYAiABKAVSDWNyZWRpdENhcmRDdnYSPQobY3JlZGl0X2NhcmRfZXhwaXJhdGlvbl95ZWFyGAMgASgFUhhjcmVkaXRDYXJkRXhwaXJhdGlvblllYXISPwocY3JlZGl0X2NhcmRfZXhwaXJhdGlvbl9tb250aBgEIAEoBVIZY3JlZGl0Q2FyZEV4cGlyYXRpb25Nb250aCJ5Cg1DaGFyZ2VSZXF1ZXN0EioKBmFtb3VudBgBIAEoCzISLmhpcHN0ZXJzaG9wLk1vbmV5UgZhbW91bnQSPAoLY3JlZGl0X2NhcmQYAiABKAsyGy5oaXBzdGVyc2hvcC5DcmVkaXRDYXJkSW5mb1IKY3JlZGl0Q2FyZCI3Cg5DaGFyZ2VSZXNwb25zZRIlCg50cmFuc2FjdGlvbl9pZBgBIAEoCVINdHJhbnNhY3Rpb25JZCJeCglPcmRlckl0ZW0SKQoEaXRlbRgBIAEoCzIVLmhpcHN0ZXJzaG9wLkNhcnRJdGVtUgRpdGVtEiYKBGNvc3QYAiABKAsyEi5oaXBzdGVyc2hvcC5Nb25leVIEY29zdCKCAgoLT3JkZXJSZXN1bHQSGQoIb3JkZXJfaWQYASABKAlSB29yZGVySWQSMAoUc2hpcHBpbmdfdHJhY2tpbmdfaWQYAiABKAlSEnNoaXBwaW5nVHJhY2tpbmdJZBI3Cg1zaGlwcGluZ19jb3N0GAMgASgLMhIuaGlwc3RlcnNob3AuTW9uZXlSDHNoaXBwaW5nQ29zdBI/ChBzaGlwcGluZ19hZGRyZXNzGAQgASgLMhQuaGlwc3RlcnNob3AuQWRkcmVzc1IPc2hpcHBpbmdBZGRyZXNzEiwKBWl0ZW1zGAUgAygLMhYuaGlwc3RlcnNob3AuT3JkZXJJdGVtUgVpdGVtcyJkChxTZW5kT3JkZXJDb25maXJtYXRpb25SZXF1ZXN0EhQKBWVtYWlsGAEgASgJUgVlbWFpbBIuCgVvcmRlchgCIAEoCzIYLmhpcHN0ZXJzaG9wLk9yZGVyUmVzdWx0UgVvcmRlciLVAQoRUGxhY2VPcmRlclJlcXVlc3QSFwoHdXNlcl9pZBgBIAEoCVIGdXNlcklkEiMKDXVzZXJfY3VycmVuY3kYAiABKAlSDHVzZXJDdXJyZW5jeRIuCgdhZGRyZXNzGAMgASgLMhQuaGlwc3RlcnNob3AuQWRkcmVzc1IHYWRkcmVzcxIUCgVlbWFpbBgFIAEoCVIFZW1haWwSPAoLY3JlZGl0X2NhcmQYBiABKAsyGy5oaXBzdGVyc2hvcC5DcmVkaXRDYXJkSW5mb1IKY3JlZGl0Q2FyZCJEChJQbGFjZU9yZGVyUmVzcG9uc2USLgoFb3JkZXIYASABKAsyGC5oaXBzdGVyc2hvcC5PcmRlclJlc3VsdFIFb3JkZXIiLgoJQWRSZXF1ZXN0EiEKDGNvbnRleHRfa2V5cxgBIAMoCVILY29udGV4dEtleXMiLwoKQWRSZXNwb25zZRIhCgNhZHMYASADKAsyDy5oaXBzdGVyc2hvcC5BZFIDYWRzIjsKAkFkEiEKDHJlZGlyZWN0X3VybBgBIAEoCVILcmVkaXJlY3RVcmwSEgoEdGV4dBgCIAEoCVIEdGV4dDLKAQoLQ2FydFNlcnZpY2USPAoHQWRkSXRlbRIbLmhpcHN0ZXJzaG9wLkFkZEl0ZW1SZXF1ZXN0GhIuaGlwc3RlcnNob3AuRW1wdHkiABI7CgdHZXRDYXJ0EhsuaGlwc3RlcnNob3AuR2V0Q2FydFJlcXVlc3QaES5oaXBzdGVyc2hvcC5DYXJ0IgASQAoJRW1wdHlDYXJ0Eh0uaGlwc3RlcnNob3AuRW1wdHlDYXJ0UmVxdWVzdBoSLmhpcHN0ZXJzaG9wLkVtcHR5IgAygwEKFVJlY29tbWVuZGF0aW9uU2VydmljZRJqChNMaXN0UmVjb21tZW5kYXRpb25zEicuaGlwc3RlcnNob3AuTGlzdFJlY29tbWVuZGF0aW9uc1JlcXVlc3QaKC5oaXBzdGVyc2hvcC5MaXN0UmVjb21tZW5kYXRpb25zUmVzcG9uc2UiADKDAgoVUHJvZHVjdENhdGFsb2dTZXJ2aWNlEkcKDExpc3RQcm9kdWN0cxISLmhpcHN0ZXJzaG9wLkVtcHR5GiEuaGlwc3RlcnNob3AuTGlzdFByb2R1Y3RzUmVzcG9uc2UiABJECgpHZXRQcm9kdWN0Eh4uaGlwc3RlcnNob3AuR2V0UHJvZHVjdFJlcXVlc3QaFC5oaXBzdGVyc2hvcC5Qcm9kdWN0IgASWwoOU2VhcmNoUHJvZHVjdHMSIi5oaXBzdGVyc2hvcC5TZWFyY2hQcm9kdWN0c1JlcXVlc3QaIy5oaXBzdGVyc2hvcC5TZWFyY2hQcm9kdWN0c1Jlc3BvbnNlIgAyqgEKD1NoaXBwaW5nU2VydmljZRJJCghHZXRRdW90ZRIcLmhpcHN0ZXJzaG9wLkdldFF1b3RlUmVxdWVzdBodLmhpcHN0ZXJzaG9wLkdldFF1b3RlUmVzcG9uc2UiABJMCglTaGlwT3JkZXISHS5oaXBzdGVyc2hvcC5TaGlwT3JkZXJSZXF1ZXN0Gh4uaGlwc3RlcnNob3AuU2hpcE9yZGVyUmVzcG9uc2UiADK3AQoPQ3VycmVuY3lTZXJ2aWNlElsKFkdldFN1cHBvcnRlZEN1cnJlbmNpZXMSEi5oaXBzdGVyc2hvcC5FbXB0eRorLmhpcHN0ZXJzaG9wLkdldFN1cHBvcnRlZEN1cnJlbmNpZXNSZXNwb25zZSIAEkcKB0NvbnZlcnQSJi5oaXBzdGVyc2hvcC5DdXJyZW5jeUNvbnZlcnNpb25SZXF1ZXN0GhIuaGlwc3RlcnNob3AuTW9uZXkiADJVCg5QYXltZW50U2VydmljZRJDCgZDaGFyZ2USGi5oaXBzdGVyc2hvcC5DaGFyZ2VSZXF1ZXN0GhsuaGlwc3RlcnNob3AuQ2hhcmdlUmVzcG9uc2UiADJoCgxFbWFpbFNlcnZpY2USWAoVU2VuZE9yZGVyQ29uZmlybWF0aW9uEikuaGlwc3RlcnNob3AuU2VuZE9yZGVyQ29uZmlybWF0aW9uUmVxdWVzdBoSLmhpcHN0ZXJzaG9wLkVtcHR5IgAyYgoPQ2hlY2tvdXRTZXJ2aWNlEk8KClBsYWNlT3JkZXISHi5oaXBzdGVyc2hvcC5QbGFjZU9yZGVyUmVxdWVzdBofLmhpcHN0ZXJzaG9wLlBsYWNlT3JkZXJSZXNwb25zZSIAMkgKCUFkU2VydmljZRI7CgZHZXRBZHMSFi5oaXBzdGVyc2hvcC5BZFJlcXVlc3QaFy5oaXBzdGVyc2hvcC5BZFJlc3BvbnNlIgBiBnByb3RvMw==
---
apiVersion: apimanagement.gloo.solo.io/v2
kind: ApiDoc
metadata:
  name: adservice
  namespace: online-boutique
spec:
  graphql:
    schemaDefinition: |-
      type Ad { redirect_url: String text: String }

      type AdList { ads: [Ad] }

      type Query {
        GetAds: AdList
      }
---
apiVersion: apimanagement.gloo.solo.io/v2
kind: ApiDoc
metadata:
  name: productservice
  namespace: online-boutique
spec:
  graphql:
    schemaDefinition: |-
      type Price { currency_code: String units: String nanos: Int }

      type Product { 
        id: String
        name: String
        description: String
        picture: String
        categories: [String]
        price_usd: Price
      }

      type ProductList { products: [Product] }

      type Query {
        ListProducts: ProductList
      }
---
apiVersion: apimanagement.gloo.solo.io/v2
kind: ApiDoc
metadata:
  name: currencyservice
  namespace: online-boutique
spec:
  graphql:
    schemaDefinition: |-
      type CurrencyCodes { currency_codes: [String] }
      type Query {
        GetCurrencies: [CurrencyCodes]
      }
