apiVersion: security.policy.gloo.solo.io/v2
kind: CORSPolicy
metadata:
  name: cors-policy
  namespace: online-boutique
spec:
  applyToRoutes:
    - route:
        name: products
        namespace: online-boutique
        cluster: cluster-1
  config:
    allowCredentials: true
    allowHeaders:
    - content-type
    - x-apollo-tracing
    allowMethods:
    - POST
    allowOrigins:
    - regex: '.*'