apiVersion: apimanagement.gloo.solo.io/v2
kind: GraphQLResolverMap
metadata:
  name: resolvers
  namespace: online-boutique
spec:
  extensions:
    grpcSchemaSelector:
      name: hipster-schema
      namespace: online-boutique
      cluster: cluster-1
  types:
    Query:
      fields:
        ListProducts:
          resolvers:
          - grpcResolver:
              destinations:
              - port:
                  number: 3550
                ref:
                  cluster: cluster-1
                  name: productcatalogservice
                  namespace: backend-apis
              request:
                service: hipstershop.ProductCatalogService
                method: ListProducts
                outgoingMessage:
                  json: {}
---
apiVersion: apimanagement.gloo.solo.io/v2
kind: GraphQLResolverMap
metadata:
  name: adservice
  namespace: online-boutique
spec:
  extensions:
    grpcSchemaSelector:
      name: hipster-schema
      namespace: online-boutique
      cluster: cluster-1
  types:
    Query:
      fields:
        GetAds:
          resolvers:
          - grpcResolver:
              destinations:
              - port:
                  number: 9555
                ref:
                  cluster: cluster-1
                  name: adservice
                  namespace: backend-apis
              request:
                service: hipstershop.AdService
                method: GetAds
                outgoingMessage:
                  json: {}
---
apiVersion: apimanagement.gloo.solo.io/v2
kind: GraphQLResolverMap
metadata:
  name: cartservice
  namespace: online-boutique
spec:
  extensions:
    grpcSchemaSelector:
      name: hipster-schema
      namespace: online-boutique
      cluster: cluster-1
  types:
    Query:
      fields:
        GetCart:
          variables:
            user_id:
              graphqlArg: user_id
          resolvers:
          - grpcResolver:
              destinations:
              - port:
                  number: 7070
                ref:
                  cluster: cluster-1
                  name: cartservice
                  namespace: backend-apis
              request:
                service: hipstershop.CartService
                method: GetCart
                outgoingMessage:
                  jq: '{user_id: .user_id}'