apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: frontend
  namespace: web-team
spec:
  hosts:
    - '*'
  virtualGateways:
    - name: north-south-gw
      namespace: ops-team
      cluster: mgmt
  workloadSelectors: []
  http:
    - name: frontend
      labels:
        rate-limit: "true"
      forwardTo:
        destinations:
          - ref:
              name: frontend
              namespace: web-ui
              cluster: cluster1
            port:
              number: 80
---
apiVersion: admin.gloo.solo.io/v2
kind: RateLimitServerSettings
metadata:
  name: frontend
  namespace: web-team
spec:
  destinationServer:
    port:
      number: 8083
    ref:
      name: rate-limiter
      namespace: gloo-mesh-addons
      cluster: cluster1
---
apiVersion: trafficcontrol.policy.gloo.solo.io/v2
kind: RateLimitClientConfig
metadata:
  name: frontend
  namespace: web-team
spec:
  raw:
    rateLimits:
    - actions:
      - genericKey:
          descriptorValue: counter
---
apiVersion: admin.gloo.solo.io/v2
kind: RateLimitServerConfig
metadata:
  name: frontend
  namespace: web-team
spec:
  destinationServers:
  - ref:
      cluster: cluster1
      name: rate-limiter
      namespace: gloo-mesh-addons
    port:
      name: grpc
  raw:
    descriptors:
    - key: generic_key
      rateLimit:
        requestsPerUnit: 2
        unit: MINUTE
      value: counter
---
apiVersion: trafficcontrol.policy.gloo.solo.io/v2
kind: RateLimitPolicy
metadata:
  name: frontend
  namespace: web-team
spec:
  applyToRoutes:
  - route:
      labels:
        rate-limit: "true"
  config:
    serverSettings:
      name: frontend
      namespace: web-team
      cluster: mgmt
    ratelimitClientConfig:
      name: frontend
      namespace: web-team
      cluster: mgmt
    ratelimitServerConfig:
      name: frontend
      namespace: web-team
      cluster: mgmt
    phase:
      postAuthz:
        priority: 3