apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-setup
  namespace: vault
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-setup-admin
  namespace: vault
subjects:
- kind: ServiceAccount
  name: vault-setup
  namespace: vault
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
# bitnami/kubectl:latest
apiVersion: v1
kind: Pod
metadata:
  name:  vault-setup
  namespace: vault
  labels:
    app: vault-setup
spec:
  serviceAccountName: vault-setup
  containers:
    - command:
        - sleep
        - 20h
      image: vault:latest
      name: vault-setup