#!/usr/bin/env bash

set -Eeuo pipefail
trap cleanup SIGINT SIGTERM ERR EXIT 

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)

usage() {
    cat <<EOF
Usage: $(basename "${BASH_SOURCE[0]}") [-h] version

This script will print out the list of images required for an air-gapped installation of Gloo Mesh Enterprise.
The version argument is required.

Available options:

-h, --help      Print this help and exit
-v, --verbose   Print script debug info
EOF
    exit
}

cleanup() {
    trap - SIGINT SIGTERM ERR EXIT
    # nothing to do
    if [[ -z $VERSION ]]; then
        return
    fi
    rm *.tgz
    rm -rf enterprise-agent || true
    rm -rf gloo-mesh-agent || true
    rm -rf gloo-mesh-enterprise || true
    rm -rf gloo-platform || true
    rm .images.out
}

setup_colors() {
    if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
        NOFORMAT='\033[0m' RED='\033[0;31m' GREEN='\033[0;32m' ORANGE='\033[0;33m' BLUE='\033[0;34m' PURPLE='\033[0;35m' CYAN='\033[0;36m' YELLOW='\033[1;33m'
    else
        NOFORMAT='' RED='' GREEN='' ORANGE='' BLUE='' PURPLE='' CYAN='' YELLOW=''
    fi
}

msg() {
    echo >&2 -e "${1-}"
}

die() {
    local msg=$1
    local code=${2-1} # default exit status 1
    msg "$msg"
    exit "$code"
}

parse_params() {
    # default values of variables set from params
    pull=0
    param=''
    VERSION=''

    while :; do
        case "${1-}" in 
        -h | --help) usage ;;
        -v | --verbose) set -x ;;
        -p | --pull) pull=1 ;;
        --no-color) NO_COLOR=1 ;;
        -?*) die "Unknown option: $1" ;;
        *) break ;;
        esac
        shift
    done

    args=("$@")

    # check required params and arguments
    [[ ${#args[@]} -eq 0 ]] && die "Missing required argument - version"

    return 0
}

parse_params "$@"
setup_colors

VERSION="${args[0]}"
OS=$(uname)
JSON_FLAG='-j'
if [ $OS == 'Darwin' ]; then
    JSON_FLAG="-o=json"
fi

# Script logic
echo "Finding images for Gloo Mesh Enterprise version ${VERSION}"
if [[ $VERSION == 1* ]]; then
    echo ""
    echo "###################################"
    echo "# Getting enterprise-agent images #"
    echo "###################################"
    wget -q https://storage.googleapis.com/gloo-mesh-enterprise/enterprise-agent/enterprise-agent-${VERSION}.tgz
    tar zxf enterprise-agent-${VERSION}.tgz
    find enterprise-agent -name "values.yaml" | while read file; do 
        cat $file | yq eval $JSON_FLAG | jq -r '.. | .image? | select(. != null) | (if .registry then (if .registry == "docker.io" then "docker.io/library" else .registry end) + "/" else "" end) + .repository + ":" + (.tag | tostring)'
    done | sort -u | tee .images.out
elif [[ $VERSION == 2.0* || $VERSION == 2.1* || $VERSION == 2.2* || $VERSION == 2.3* ]]; then
    echo ""
    echo "###################################"
    echo "# Getting gloo-mesh-agent images #"
    echo "###################################"
    wget -q https://storage.googleapis.com/gloo-mesh-enterprise/gloo-mesh-agent/gloo-mesh-agent-${VERSION}.tgz
    tar zxf gloo-mesh-agent-${VERSION}.tgz
    find gloo-mesh-agent -name "values.yaml" | while read file; do
        cat $file | yq eval $JSON_FLAG | jq -r '.. | .image? | select(. != null) | (if .registry then (if .registry == "docker.io" then "docker.io/library" else .registry end) + "/" else "" end) + .repository? + ":" + (.tag? | tostring)'
    done | sort -u | tee .images.out
fi

echo ""
echo "###################################"
echo "# Getting Gloo Mesh images        #"
echo "###################################"
if [[ $VERSION == 2.0* || $VERSION == 2.1* || $VERSION == 2.2* || $VERSION == 2.3* ]]; then
    wget -q https://storage.googleapis.com/gloo-mesh-enterprise/gloo-mesh-enterprise/gloo-mesh-enterprise-${VERSION}.tgz
    tar zxf gloo-mesh-enterprise-${VERSION}.tgz
    find gloo-mesh-enterprise -name "values.yaml" | while read file; do
        cat $file | yq eval $JSON_FLAG | jq -r '.. | .image? | select(. != null) | (if .registry then (if .registry == "docker.io" then "docker.io/library" else .registry end) + "/" else "" end) + .repository? + ":" + (.tag? | tostring)'
    done | sort -u | tee -a .images.out
else
    wget -q https://storage.googleapis.com/gloo-platform/helm-charts/gloo-platform-${VERSION}.tgz
    tar zxf gloo-platform-${VERSION}.tgz
    find gloo-platform -name "values.yaml" | while read file; do
        cat $file | yq eval $JSON_FLAG | jq -r '.. | .image? | select(. != null) | (if .registry then (if .registry == "docker.io" then "docker.io/library" else .registry end) + "/" else "" end) + .repository? + .repo? + ":" + (.tag? | tostring)'
    done | sort -u | tee -a .images.out
fi


echo ""
echo "#######################################"
echo "# Getting Solo distributions of Istio #"
echo "#######################################"
echo us-docker.pkg.dev/gloo-mesh/istio-workshops/pilot:1.20.2-solo | tee -a .images.out
echo us-docker.pkg.dev/gloo-mesh/istio-workshops/proxyv2:1.20.2-solo | tee -a .images.out


if [ $pull == 1 ]; then
  echo ""
  echo "Pulling images locally"
  cat .images.out | while read image; do
    src=$(echo $image | sed 's/^docker\.io\///g')
    dest=$(echo $image | awk -F/ '{ if(NF>2){ print $2"/"$3}else{if($1=="docker.io"){print $2}else{print $1"/"$2}}}')
    docker pull $image 
  done
fi

# Cleanup
cleanup
