{{- if and (not .Values.telemetryGateway.configMap.create) (.Values.telemetryGateway.enabled) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.telemetryGateway.fullnameOverride }}-config
  namespace: {{ .Release.Namespace }}
data:
  relay: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
            max_recv_msg_size_mib: 12
            tls:
              cert_file: /etc/otel-certs/tls.crt
              key_file: /etc/otel-certs/tls.key
        {{- if .Values.telemetryGatewayCustomization.reloadTlsCertificate }}
              reload_interval: {{ .Values.telemetryGatewayCustomization.reloadTlsCertificate }}
        {{- end }}
      prometheus:
        config:
          scrape_configs:
          # Scrape the collector itself
          - job_name: opentelemetry-collector
            scrape_interval: 15s
            static_configs:
            - targets:
              - ${MY_POD_IP}:8888
      {{- if .Values.telemetryGatewayCustomization.extraReceivers }}
      # Custom receivers
      {{- .Values.telemetryGatewayCustomization.extraReceivers | toYaml | nindent 6 }}
      {{- end }}

    processors:
      {{- if .Values.telemetryGatewayCustomization.extraProcessors }}
      # Custom processors
      {{- .Values.telemetryGatewayCustomization.extraProcessors | toYaml | nindent 6 }}
      {{- end }}

    exporters:
      prometheus:
        endpoint: 0.0.0.0:9091
      {{- if .Values.telemetryGatewayCustomization.extraExporters }}
      # Custom exporters
      {{- .Values.telemetryGatewayCustomization.extraExporters | toYaml | nindent 6 }}
      {{- end }}

    extensions:
      health_check: {}
      memory_ballast:
        size_in_percentage: 20

    service:
      telemetry:
        {{- .Values.telemetryGatewayCustomization.telemetry | toYaml | nindent 8 }}
      extensions:
      - health_check
      - memory_ballast
      pipelines:
    
        {{- if not .Values.telemetryGatewayCustomization.disableDefaultPipeline }}
        metrics:
          receivers:
          - otlp
          - prometheus
          processors:
            - memory_limiter
            - batch
          exporters:
          - prometheus
        {{- end }}
    
        {{- if .Values.telemetryGatewayCustomization.extraPipelines }}
        # Custom pipelines
        {{- .Values.telemetryGatewayCustomization.extraPipelines | toYaml | nindent 8 }}
        {{- end }}
  {{- end -}}
