apiVersion: v1
kind: Namespace
metadata:
  name: grafana
  labels:
    istio.io/rev: 1-20
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: grafana
data:
  admin-user: YWRtaW4=
  admin-password: c3VwZXJzZWNyZXRwYXNzd29yZA==
type: Opaque
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: grafana
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 6.58.7
    chart: grafana
    helm:
      values: |
        admin:
          existingSecret: grafana
        service:
          port: 3000
          type: ClusterIP
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - access: proxy
              editable: true
              isDefault: false
              jsonData:
                timeInterval: 5s
              name: Prometheus
              orgId: 1
              type: prometheus
              url: http://prometheus.istio-system:9090
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
              - name: istio
                orgId: 1
                disableDeletion: false
                folder: istio
                type: file
                disableDeletion: false
                options:
                  path: /var/lib/grafana/dashboards/istio
              - name: solo
                orgId: 1
                disableDeletion: false
                folder: istio
                type: file
                disableDeletion: false
                options:
                  path: /var/lib/grafana/dashboards/solo
              - name: kubernetes
                orgId: 1
                disableDeletion: false
                folder: kubernetes
                type: file
                disableDeletion: false
                options:
                  path: /var/lib/grafana/dashboards/kubernetes
                
        dashboardsConfigMaps:
          istio: istio-grafana-dashboards
          solo: solo-istio-dashboard
          kubernetes: kubernetes-dashboard
        defaultDashboardsEnabled: false
        grafana.ini:
          auth.anonymous:
            enabled: true
          server:
            root_url: http://%(domain)s:%(http_port)s/grafana
            serve_from_sub_path: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true