{
 "title": "Gloo Mesh Operations",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Gloo Mesh Mgmt Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Gloo Mesh vCPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"gloo-mesh-mgmt-server\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Gloo Mesh Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"gloo-mesh-mgmt-server\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{container=\"gloo-mesh-mgmt-server\", resource=\"memory\"})",
     "legendFormat": "limit"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{container=\"gloo-mesh-mgmt-server\", resource=\"memory\"})",
     "legendFormat": "reserved"
    }
   ]
  },
  {
   "title": "Redis Sync Errors (last 10m)",
   "type": "stat",
   "description": "Number of errors when trying to sync with Redis",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(gloo_mesh_redis_sync_err{app=\"gloo-mesh-mgmt-server\", job=\"kubernetes-pods\"}[10m]))"
    }
   ]
  },
  {
   "title": "Gloo Mesh Mgmt Server Memory Limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits{container=\"gloo-mesh-mgmt-server\", resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Gloo Mesh Tanslator Concurrency",
   "type": "stat",
   "description": "Number of translators that can run concurrently",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gloo_mesh_translator_concurrency{job=\"kubernetes-service-endpoints\"})"
    }
   ]
  },
  {
   "title": "Gloo Mesh Mgmt Server Memory Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{container=\"gloo-mesh-mgmt-server\", resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Workspace Errors",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(translation_error{job=\"kubernetes-pods\"}) by(pod,workspace,namespace)"
    }
   ]
  },
  {
   "title": "Translation Warnings Per Workspace",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 10, "y": 9 },
   "targets": [
    {
     "expr": "sum(translation_warning{job=\"kubernetes-pods\"}) by (pod,namespace,workspace,gvk)"
    }
   ]
  },
  {
   "title": "Total Translation Times Histogram",
   "type": "bargauge",
   "description": "Count of translations times that were in a given time in seconds",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gloo_mesh_reconciler_time_sec_bucket{job=\"kubernetes-pods\",reconciler_name=\"translator\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Translation Time p95 (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(gloo_mesh_reconciler_time_sec_bucket[5m])) by (le,reconciler_name))",
     "legendFormat": "{{reconciler_name}}"
    }
   ]
  },
  { "title": "Agent Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Agents Connected",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(relay_pull_clients_connected{app=\"gloo-mesh-mgmt-server\"}) / count(relay_pull_clients_connected{app=\"gloo-mesh-mgmt-server\"})"
    }
   ]
  },
  {
   "title": "Agents Connected To each Management Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 3, "y": 28 },
   "targets": [
    {
     "expr": "sum(relay_pull_clients_connected{app=\"gloo-mesh-mgmt-server\",job=\"kubernetes-pods\"})by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Agents Connected To Each Mgmt Pod",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 11, "y": 28 },
   "targets": [
    {
     "expr": "sum(relay_pull_clients_connected{job=\"kubernetes-pods\", app=\"gloo-mesh-mgmt-server\"}) by (pod,cluster)"
    }
   ]
  },
  {
   "title": "Agent Clusters Not Warmed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(relay_push_clients_warmed{job=\"kubernetes-pods\"} == 0) by(cluster))"
    }
   ]
  },
  {
   "title": "Total Agent Connected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(relay_pull_clients_connected{job=\"kubernetes-pods\"})"
    }
   ]
  },
  { "title": "High Level Mesh Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Total Requests Per Second in Mesh",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{app=\"gloo-mesh-mgmt-server\"}[5m])), 0.001)",
     "legendFormat": "{{destination_app}}"
    }
   ]
  }
 ]
}